lightbend/genjavadoc

README.md

Hat tip to [lpiepiora](http://stackoverflow.com/users/480975/lpiepiora) for [this information](http://stackoverflow.com/questions/24304452/how-to-use-genjavadoc-plugin-for-sbt/24304828?noredirect=1#24304828).

Include instructions in README how to add config and settings to a project.

---

plugin/src/main/scala/com/typesafe/genjavadoc/AST.scala
plugin/src/main/scala/com/typesafe/genjavadoc/BasicTransform.scala
project/Build.scala
tests/expected_output/akka/rk/buh/is/it/DeprecatedNoComment.java
tests/expected_output/akka/rk/buh/is/it/DontTouchThis.java
tests/src/test/scala/scala/javadoc/test.scala

Fixes #60 
Suboptimal list concatenations here and there, should I play around with `reverse` tricks?

Scala @deprecated now generates javadoc @deprecated

---

.travis.yml
plugin/src/main/scala/com/typesafe/genjavadoc/Output.scala
project/Build.scala
project/build.properties
project/plugins.sbt
tests/src/test/scala/scala/javadoc/TheSpec.scala

Also use sbt-git for deriving versions.

Support scala 2.12.0-M3

---

README.md
project/Build.scala

Fix deprecated defaultSettings in the build and update readme

---

.travis.yml
plugin/src/test/scala/com/typesafe/genjavadoc/SignatureSpec.scala
project/Build.scala

Support Scala 2.12.0-M5

---

README.md

I think this may improve the new developer experience.

Updated sample configuration.

---

plugin/src/test/resources/patches/2.12.2.patch
project/Build.scala

Resolves https://github.com/typesafehub/genjavadoc/issues/100

Support Scala 2.12.2

---

project/Build.scala

It seems 2.11.11 just works, good :)

Support Scala 2.11.11

---

RELEASING.md

Add releasing instructions

---

plugin/src/test/resources/patches/2.13.0.patch
plugin/src/test/scala/com/typesafe/genjavadoc/BasicSpec.scala

handle `2.13.0-pre-` versions with a generic 2.13.0.patch file

be 2.13 community build friendly

---

plugin/src/test/resources/patches/2.13.0-M3.patch

by supporting Scala nightly version numbers in general

fix test failure in Scala community build

---

.travis.yml
build.sbt
plugin/src/main/scala/com/typesafe/genjavadoc/JavaSig.scala
plugin/src/test/resources/patches/2.13.0.patch
plugin/src/test/scala/com/typesafe/genjavadoc/SignatureSpec.scala

note that I special-cased #143 to make this green.
I investigated to the point where I became convinced it wasn't a blocker for now, but the ticket remains open

support Scala 2.13.0-M5 (drop M4 support)

---

.travis.yml
build.sbt
plugin/src/main/scala-2.11/com/typesafe/genjavadoc/NeedsJavaSig.scala
plugin/src/main/scala-2.12/com/typesafe/genjavadoc/NeedsJavaSig.scala
plugin/src/main/scala-2.13/com/typesafe/genjavadoc/Comments.scala
plugin/src/main/scala-2.13/com/typesafe/genjavadoc/NeedsJavaSig.scala
plugin/src/main/scala/com/typesafe/genjavadoc/AST.scala
plugin/src/main/scala/com/typesafe/genjavadoc/BaseComments.scala
plugin/src/main/scala/com/typesafe/genjavadoc/BasicTransform.scala
plugin/src/main/scala/com/typesafe/genjavadoc/JavaSig.scala
plugin/src/main/scala/com/typesafe/genjavadoc/Output.scala
plugin/src/main/scala/com/typesafe/genjavadoc/Plugin.scala
plugin/src/test/resources/patches/2.13.0.patch
plugin/src/test/scala/com/typesafe/genjavadoc/SignatureSpec.scala
plugin/src/test/scala/com/typesafe/genjavadoc/util/CompilerSpec.scala
project/build.properties

~~context: making genjavadoc green again in the 2.13 community build (in preparation for 2.13.0-RC1)~~
RC1 is out, let's go!

support 2.13.0-RC1

---

.travis.yml
build.sbt

Scala 2.13.0-RC2 (#172)

---

.travis.yml
build.sbt

Upgrade to Scala 2.13.0

---

.travis.yml

This is a first step in releasing from travis, #128

Install JDK from jabba

---

.travis.yml
src/main/scala/com/typesafe/genjavadoc/JavaSig.scala
src/test/resources/expected_output/basic/akka/persistence/testkit/EventStorage$.java
src/test/resources/expected_output/basic/akka/persistence/testkit/EventStorage.java
src/test/resources/expected_output/basic/akka/persistence/testkit/JournalOperation.java
src/test/resources/expected_output/basic/akka/persistence/testkit/ProcessingPolicy$.java
src/test/resources/expected_output/basic/akka/persistence/testkit/ProcessingPolicy.java
src/test/resources/input/basic/akka/persistence/testkit/EventStorage.scala
src/test/resources/input/basic/akka/persistence/testkit/ProcessingPolicy.scala
src/test/resources/patches/2.12.10.patch
src/test/resources/patches/2.12.11.patch
src/test/resources/patches/2.12.12.patch
src/test/resources/patches/2.12.3.patch
src/test/resources/patches/2.12.4.patch
src/test/resources/patches/2.12.5.patch
src/test/resources/patches/2.12.6.patch
src/test/resources/patches/2.12.7.patch
src/test/resources/patches/2.12.8.patch
src/test/resources/patches/2.12.9.patch
src/test/resources/patches/2.13.0.patch
src/test/resources/patches/2.13.1.patch
src/test/resources/patches/2.13.2.patch

Tested that this indeed fixes the build failure at
https://github.com/akka/akka/issues/28784

Fix corner case found in Akka Persistence Testkit

---

.travis.yml
build.sbt
src/test/resources/patches/2.13.3.patch

(also, support 2.13.3 nightlies)

Scala 2.13.2 is here

---

.travis.yml
build.sbt

Scala 2.13.4 support

---

src/test/resources/patches/2.12.14.patch

needed for https://github.com/scala/community-build/pull/1340

add support for 2.12.14 nightlies

---

.travis.yml
build.sbt
src/test/resources/patches/2.13.7.patch

nightlies aspect tested locally using dbuild

add Scala 2.13.6 to crossbuild; also support 2.13.7 nightlies

---

CONTRIBUTING.md
README.md
RELEASING.md
build.sbt

build: remove last traces of travis in documentation

---

.github/workflows/validate.yml
build.sbt
src/test/resources/patches/2.13.8.patch

and add support for Scala 2.13.8 nightlies

add Scala 2.13.7 to crossbuild

---

.github/workflows/validate.yml
build.sbt
src/test/resources/patches/2.13.9.patch

and add support for Scala 2.13.9 nightlies

add Scala 2.13.8 to crossbuild
