lightbend/genjavadoc

plugin/src/main/scala/com/typesafe/genjavadoc/AST.scala
tests/expected_output/akka/rk/buh/is/it/A.java
tests/src/test/scala/scala/javadoc/test.scala

With recent versions of javadoc, checks are made to ensure that throws
clasues exist for any javadoc @throws tags. This patch converts Scala
@throws annotations to the Java throws clause so that these checks can
pass.

Convert Scala @throws annotations to Java throws clauses

---

.travis.yml
javaOut/src/test/scala/scala/javadoc/SignatureSpec.scala
plugin/src/main/scala/com/typesafe/genjavadoc/AST.scala
project/Build.scala

For now this is on the same level as for the other supported Scala
versions. Default methods (which can be produced by M4) are still
translated like abstract interface methods.

Add support for Scala 2.12.0-M4

---

plugin/src/main/scala/com/typesafe/genjavadoc/Output.scala
plugin/src/test/resources/expected_output/basic/akka/rk/buh/is/it/Reserved.java
plugin/src/test/resources/expected_output/basic/akka/rk/buh/is/it/ReservedImpl$.java
plugin/src/test/resources/expected_output/basic/akka/rk/buh/is/it/ReservedImpl.java
plugin/src/test/resources/input/basic/test.scala

Currently inherited methods and static forwarders are not filtered for java keywords, causing errors in javadoc. This PR removes such reserved-word methods.
Fixes #81.
Tested on latest Akka master.

Mangle static forwarders

---

.travis.yml
plugin/src/main/scala/com/typesafe/genjavadoc/BasicTransform.scala
plugin/src/main/scala/com/typesafe/genjavadoc/Plugin.scala
plugin/src/test/resources/expected_output/basic/akka/rk/buh/is/it/A.java
plugin/src/test/resources/patches/2.12.0-RC1.patch
plugin/src/test/scala/com/typesafe/genjavadoc/BasicSpec.scala
project/Build.scala

- The plugin now has to run after `fields` instead of `uncurry`.
- The ordering of synthetic accessors is different. Module accessors
appear at the beginning the surrounding scope and have the same
position as the module, so we do not advance the position anymore
for them.
One test still fails because of other differences in ordering. The
result looks correct and will likely need a different expected outcome
for post-fields-refactoring Scala versions.

Provide compatibility with Scala 2.12.0-RC1

---

plugin/src/main/scala-2.10/com/typesafe/genjavadoc/Comments.scala
plugin/src/main/scala-2.11/com/typesafe/genjavadoc/Comments.scala
plugin/src/main/scala-2.12/com/typesafe/genjavadoc/Comments.scala
plugin/src/main/scala/com/typesafe/genjavadoc/BaseComments.scala
project/Build.scala

Use 2.11 interface for 2.12.0, as it's identical.
From 2.12.1 on, there's a hook method that can be
used instead of copy/paste polymorphism.
One test failure due to a change in how members are sorted.
PS: since sbt 0.13.8, there's no need to manually add
versioned source files. Sadly, we need a special case for 2.12.0

Adapt to 2.12.1

---

project/Build.scala

this was failing when "scala-2.13" appeared at the start of the name
of an enclosing directory, e.g. if an enclosing directory happened to
be called "scala-2.13.x-community-build", but surely that would never
happen, right?

fix a pathname handling bug in the build

---

plugin/src/main/scala/com/typesafe/genjavadoc/AST.scala
plugin/src/main/scala/com/typesafe/genjavadoc/Output.scala
plugin/src/test/resources/expected_output/basic/akka/rk/buh/is/it/A.java
plugin/src/test/resources/expected_output/basic/akka/rk/buh/is/it/AnAbstractTypeRef.java
plugin/src/test/resources/expected_output/basic/akka/rk/buh/is/it/ClassWithInner.java
plugin/src/test/resources/expected_output/basic/akka/rk/buh/is/it/CompressionProtocol$.java
plugin/src/test/resources/expected_output/basic/akka/rk/buh/is/it/CompressionProtocol.java
plugin/src/test/resources/expected_output/basic/akka/rk/buh/is/it/DontTouchThis.java
plugin/src/test/resources/expected_output/strict_visibility/org/example/Clazz.java
plugin/src/test/resources/expected_output/strict_visibility/org/example/PublicClazz.java
plugin/src/test/resources/input/basic/test.scala

When a class (i.e. `ClassWithInner`) contains another class (i.e. `Foo`) with
a companion object, the companion object class was not properly flattened with
the explicit class, leading to 2 inner classes (and thus invalid Java code)

Correctly flatten members of a class

---

plugin/src/test/resources/patches/2.12.5.patch
plugin/src/test/scala/com/typesafe/genjavadoc/BasicSpec.scala

by supporting Scala nightly version numbers in general
context: scala/community-builds#657

fix test failure in Scala community build

---

plugin/src/main/scala/com/typesafe/genjavadoc/JavaSig.scala

new deprecation coming in 2.12.5
caught by the Scala 2.12 community build

avoid deprecated one-argument assert in compiler

---

.travis.yml
build.sbt
plugin/src/main/scala/com/typesafe/genjavadoc/BaseComments.scala
plugin/src/main/scala/com/typesafe/genjavadoc/BasicTransform.scala
plugin/src/main/scala/com/typesafe/genjavadoc/JavaSig.scala
plugin/src/main/scala/com/typesafe/genjavadoc/Output.scala
plugin/src/test/resources/patches/2.13.0.patch
plugin/src/test/scala/com/typesafe/genjavadoc/SignatureSpec.scala

Disabled fatal warnings to accept the deprecation warnings for
`SortedSet.to` / `.from`. The alternative would be to use `rangeTo` /
`rangeFrom` and add the scala-collections-compat dependency.
Disabled the tests when running on 2.13, as scalacheck is not yet available.

Compile with 2.13.0-M4

---

plugin/src/main/scala/com/typesafe/genjavadoc/BasicTransform.scala
plugin/src/main/scala/com/typesafe/genjavadoc/Output.scala
plugin/src/test/resources/expected_output/basic/akka/actor/Identify$.java
plugin/src/test/resources/expected_output/basic/akka/actor/Identify.java
plugin/src/test/resources/expected_output/basic/akka/actor/typed/DispatcherSelector$.java
plugin/src/test/resources/expected_output/basic/akka/actor/typed/DispatcherSelector.java
plugin/src/test/resources/expected_output/basic/akka/actor/typed/Props.java
plugin/src/test/resources/input/basic/akka/actor/Actor.scala
plugin/src/test/resources/input/basic/akka/actor/typed/Props.scala
plugin/src/test/resources/patches/2.12.0.patch
plugin/src/test/resources/patches/2.12.1.patch
plugin/src/test/resources/patches/2.12.2.patch
plugin/src/test/resources/patches/2.12.3.patch
plugin/src/test/resources/patches/2.12.4.patch
plugin/src/test/resources/patches/2.12.5.patch
plugin/src/test/resources/patches/2.12.6.patch
plugin/src/test/resources/patches/2.12.7.patch
plugin/src/test/resources/patches/2.12.8.patch
plugin/src/test/resources/patches/2.12.9.patch
plugin/src/test/resources/patches/2.13.0.patch
plugin/src/test/scala/com/typesafe/genjavadoc/BasicSpec.scala
plugin/src/test/scala/com/typesafe/genjavadoc/StrictVisibilityTest.scala
plugin/src/test/scala/com/typesafe/genjavadoc/util/CompilerSpec.scala

We should create static forwarders for the methods inherited on the
companion object, not on the class itself.
Fixes #154

Fix creating static forwarders for inherited methods

---

plugin/src/main/scala/com/typesafe/genjavadoc/BasicTransform.scala
plugin/src/main/scala/com/typesafe/genjavadoc/JavaSig.scala
plugin/src/main/scala/com/typesafe/genjavadoc/Output.scala
plugin/src/test/resources/expected_output/basic/akka/actor/TypedActor$.java
plugin/src/test/resources/expected_output/basic/akka/actor/TypedActor$TypedActor.java
plugin/src/test/resources/expected_output/basic/akka/actor/TypedActor.java
plugin/src/test/resources/expected_output/basic/akka/rk/buh/is/it/A.java
plugin/src/test/resources/input/basic/akka/actor/TypedActor.scala
plugin/src/test/resources/patches/2.12.0.patch
plugin/src/test/resources/patches/2.12.1.patch
plugin/src/test/resources/patches/2.12.2.patch
plugin/src/test/resources/patches/2.12.3.patch
plugin/src/test/resources/patches/2.12.4.patch
plugin/src/test/resources/patches/2.12.5.patch
plugin/src/test/resources/patches/2.12.6.patch
plugin/src/test/resources/patches/2.12.7.patch
plugin/src/test/resources/patches/2.12.8.patch
plugin/src/test/resources/patches/2.12.9.patch
plugin/src/test/resources/patches/2.13.0.patch
plugin/src/test/scala/com/typesafe/genjavadoc/SignatureSpec.scala

Interfaces were already lifted, but the same rule
applies to classes.

Lift inner classes with same name as well

---

plugin/src/main/scala/com/typesafe/genjavadoc/AST.scala
plugin/src/test/resources/expected_output/rangepos/akka/cluster/ClusterRouterGroupSettings.java
plugin/src/test/resources/input/rangepos/akka/cluster/ClusterRouterGroupSettings.scala
plugin/src/test/scala/com/typesafe/genjavadoc/RangePosSpec.scala
plugin/src/test/scala/com/typesafe/genjavadoc/SignatureSpec.scala
plugin/src/test/scala/com/typesafe/genjavadoc/util/CompilerSpec.scala
plugin/src/test/scala/com/typesafe/genjavadoc/util/GenJavaDocCompiler.scala

Previously, `appendToComment` assumed there was either no existing comment or
an existing Javadoc comment. I ran into this situation when compiling Akka with
-Yrangepos enabled (hence the test).
This change makes `appendToComment` also work when there is an existing
C-style comment.
Certainly this could be improved further, but I wanted to focus on fixing my
immediate problem.

Make 'appendToComment' work on C-style comments

---

plugin/src/main/scala/com/typesafe/genjavadoc/Plugin.scala

When generating scaladoc, not the scala compiler is run with a limited set of
phases. Notably, it runs it without the 'fields' phase which genjavadoc
depends on, disabling genjavadoc while producing the warning
`dropping dependency on node with no phase object: fields`. When you have
`-Xfatal-warnings` enabled, this then leads to an error.
Inspired by https://github.com/HairyFotr/linter/issues/23

Don't run genjavadoc while generating scaladoc

---

build.sbt
project/plugins.sbt

While working on #168 Sonatype rejected the generated POMs because of the duplicated SCM section. It was once added by the sbt-git plugin, and another time from the `pomExtra` in the build.sbt.
I have cleaned up the build to use sbt-dynver instead and derive the extra information for the POM from sbt settings.

Derive POM from sbt settings

---

README.md
plugin/src/main/scala/com/typesafe/genjavadoc/AST.scala
plugin/src/main/scala/com/typesafe/genjavadoc/Plugin.scala
plugin/src/main/scala/com/typesafe/genjavadoc/TransformCake.scala
plugin/src/test/resources/expected_output/basic/akka/WithAnnotation.java
plugin/src/test/resources/input/basic/akka/WithAnnotation.scala
plugin/src/test/scala/com/typesafe/genjavadoc/BasicSpec.scala

Hi, we have a custom javadoc doclet that relies on some annotations to be present in Java files. In order to be able to use Scala for the code that needs to be processed with that doclet I have added very limited support that will pass annotations without any parameters to Java stubs generated by genjavadoc plugin. Can you please take a look and maybe merge it / improve it?
P.S. Are tests up-to-date? I'm not sbt user, so maybe I skipped something important but I could not get test task to pass:
```
[IJ]sbt:genjavadoc> {file:/Users/ilx/work/xebialabs/xlr-project/genjavadoc/}genjavadoc-plugin/test
[info] Updating genjavadoc-plugin...
[info] Done updating.
[info] Compiling 9 Scala sources to /Users/ilx/work/xebialabs/xlr-project/genjavadoc/plugin/target/scala-2.13.0-RC1/classes ...
[error] …
```

GH-97 Add basic support for passing annotations to the generated Java stubs

---

project/build.properties
project/plugins.sbt

Refs #193
To make sure publishing uses the expected path again. Of course it would be
better to make this work with sbt1, but I'm not sure how.

Revert back to sbt 0.13.17

---

plugin/src/main/scala/com/typesafe/genjavadoc/Plugin.scala
plugin/src/test/resources/expected_output/basic/akka/rk/buh/is/it/A.java
plugin/src/test/resources/input/basic/test.scala
plugin/src/test/resources/patches/2.12.0.patch
plugin/src/test/resources/patches/2.12.1.patch
plugin/src/test/resources/patches/2.12.10.patch
plugin/src/test/resources/patches/2.12.11.patch
plugin/src/test/resources/patches/2.12.2.patch
plugin/src/test/resources/patches/2.12.3.patch
plugin/src/test/resources/patches/2.12.4.patch
plugin/src/test/resources/patches/2.12.5.patch
plugin/src/test/resources/patches/2.12.6.patch
plugin/src/test/resources/patches/2.12.7.patch
plugin/src/test/resources/patches/2.12.8.patch
plugin/src/test/resources/patches/2.12.9.patch
plugin/src/test/resources/patches/2.13.0.patch
plugin/src/test/resources/patches/2.13.1.patch
plugin/src/test/resources/patches/2.13.2.patch

`runsAfter` is set to `fields`. However, in reality the phase
assembly algorithm used in 2.12.9 and before, also 2.13.0, places the
`GenJavadoc` phase right after `specialize`, which is valid, but probably
not intended.
With some changes in the phase assembly algorithm in 2.13.1, the
`GenJavadoc` phase was now placed right after `fields`, which caused
tests to fail.

Set compiler phase `runsBefore` to `tailcalls`

---

build.sbt

One more step in the direction of sbt-ci-release
See also https://github.com/lightbend/genjavadoc/issues/203
Needed to release 0.15 from travis (https://github.com/lightbend/genjavadoc/releases/tag/untagged-48dd919bb052b2bbdd76)

Get sonatype credentials from environment variables

---

build.sbt

This no longer appears to be necessary, and even causes problems on sbt 1.3.
See also #209

Don't explicitly clean before testing

---

README.md

Perhaps it should be in the usage example as well? #215

Mention --ignore-source-errors in README

---

.travis.yml
build.sbt

- Add support for Scala 2.13.5
- Simplify list of crossScalaVersions

Add support for Scala 2.13.5

---

src/main/scala/com/typesafe/genjavadoc/BasicTransform.scala

This started to fail with 2.13.6 as annotation.toString was just `deprecated` for the companion object. The case class symbol annotation toString itself still seems to contain the parameters.
@SethTisue do you know whether that might have been a change only in `toString` behavior between 2.13.5 and 2.13.6 or if copying over annotations from `case class` to it's generated companion object might have changed?
Fixes #286.

more robust annotation retrieval

---

build.sbt

There were some commits trying to introduce 2.12.14 but none of those change it here in the supported versions.

Support 2.12.14 in build.sbt

---

src/main/scala/com/typesafe/genjavadoc/AST.scala
src/main/scala/com/typesafe/genjavadoc/BasicTransform.scala
src/test/resources/expected_output/basic/akka/rk/buh/is/it/DontTouchThis.java
src/test/resources/input/basic/test.scala
src/test/resources/patches/2.12.18.patch
src/test/resources/patches/2.12.19.patch
src/test/resources/patches/2.12.20.patch
src/test/resources/patches/2.13.11.patch
src/test/resources/patches/2.13.12.patch
src/test/scala/com/typesafe/genjavadoc/BasicSpec.scala

Fixes https://github.com/lightbend/genjavadoc/issues/347

Support java Deprecated on Scala symbols

---

.github/workflows/validate.yml

this should make GitHub stop complaining that we're running old Node 16 based actions

CI config: bump actions versions

---

.github/workflows/release.yml
.github/workflows/validate.yml

standardize sbt-ci-release setup

---

.github/workflows/release.yml
RELEASING.md

when releasing for new Scala versions without introducing a new genjavadoc version

Avoid accidentally triggering CI release
